"""Curated festival ruleset — seed data for pan-Indian festivals.

Astronomy alone is not sufficient for festival dates; scriptural rules
determine specific windows (e.g. Lakshmi Puja in Pradosh Kaal after sunset
on Diwali). This module stores rule hints plus fixed_date values for the
current seed year (2026) so compute_daily() has something concrete to match
against.

Each entry also carries a "category" field — one of "festival", "deity",
"observance", "other" — used by the front-end to group festivals into
sections (see rangroots.app /calendar page). This is a display taxonomy,
distinct from "type" (which currently only distinguishes "main_festival";
kept for backward compatibility and possible future sub-typing).

TODO (follow-up): compute fixed_date per-year from tithi/nakshatra rules
instead of hardcoding, so this works for any year without manual updates.
Current hardcoded dates are for calendar year 2026 (India Standard Time
dates; not yet adjusted per-city per docs/build-vs-buy.md hybrid model).
"""

FESTIVALS = [
    {
        "id": "lohri",
        "name": "Lohri",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Harvest festival observed in mid-January.",
        "fixed_date": "2026-01-13",
        "description": "Bonfire-centered harvest celebration marking the seasonal turn toward longer days.",
    },
    {
        "id": "makar_sankranti",
        "name": "Makar Sankranti",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Sun's transition into Makara (Capricorn).",
        "fixed_date": "2026-01-14",
        "description": "Solar festival honoring the northward journey of the sun and acts of charity.",
    },
    {
        "id": "pongal",
        "name": "Pongal",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Tamil harvest observance aligned with Makar Sankranti season.",
        "fixed_date": "2026-01-14",
        "description": "Thanksgiving festival celebrating harvest, prosperity, and the bond between people and land.",
    },
    {
        "id": "swami_vivekananda_jayanti",
        "name": "Swami Vivekananda Jayanti",
        "type": "observance",
        "category": "observance",
        "rule_hint": "Birth anniversary observance.",
        "fixed_date": "2026-01-12",
        "description": "Day of reflection on seva, spiritual discipline, and cultural confidence.",
    },
    {
        "id": "vasant_panchami",
        "name": "Vasant Panchami",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Dedicated to Saraswati and the arrival of spring.",
        "fixed_date": "2026-01-23",
        "description": "Spring observance honoring Saraswati, learning, and artistic practice.",
    },
    {
        "id": "holi",
        "name": "Holi",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Purnima in Phalguna month.",
        "fixed_date": "2026-03-19",
        "description": "Festival of colors celebrating renewal, joy, and the victory of good over harm.",
    },
    {
        "id": "maha_shivaratri",
        "name": "Maha Shivaratri",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Night observance dedicated to Shiva.",
        "fixed_date": "2026-03-26",
        "description": "Nightlong vigil, mantra, and fasting in reverence to Shiva.",
    },
    {
        "id": "ram_navami",
        "name": "Ram Navami",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Shukla Paksha Navami in Chaitra month.",
        "fixed_date": "2026-04-01",
        "description": "Celebration of the birth of Rama with recitation, kirtan, and family worship.",
    },
    {
        "id": "ugadi",
        "name": "Ugadi",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Lunisolar new year observed in parts of South India.",
        "fixed_date": "2026-04-13",
        "end_date": "2026-04-14",
        "description": "New year observance centered on renewal, auspicious beginnings, and family meals.",
    },
    {
        "id": "vaisakhi",
        "name": "Vaisakhi",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Harvest and new year observance in North India.",
        "fixed_date": "2026-04-13",
        "end_date": "2026-04-14",
        "description": "Harvest celebration marked by gratitude, community gathering, and seasonal transition.",
    },
    {
        "id": "bodhi_day",
        "name": "Bodhi Day",
        "type": "observance",
        "category": "other",
        "rule_hint": "Buddhist observance of awakening.",
        "fixed_date": "2026-05-01",
        "description": "Buddhist day of contemplation on awakening, discipline, and compassion.",
    },
    {
        "id": "guru_purnima",
        "name": "Guru Purnima",
        "type": "observance",
        "category": "observance",
        "rule_hint": "Purnima honoring the guru-shishya tradition.",
        "fixed_date": "2026-07-21",
        "description": "Observance honoring teachers, lineages, and the transmission of knowledge.",
    },
    {
        "id": "vesak",
        "name": "Vesak",
        "type": "observance",
        "category": "other",
        "rule_hint": "Buddhist observance of the Buddha's life events.",
        "fixed_date": "2026-07-29",
        "description": "Buddhist observance remembering birth, enlightenment, and parinirvana.",
    },
    {
        "id": "raksha_bandhan",
        "name": "Raksha Bandhan",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Shravana Purnima observance.",
        "fixed_date": "2026-08-26",
        "description": "Festival celebrating sibling bonds, protection, and familial affection.",
    },
    {
        "id": "krishna_janmashtami",
        "name": "Krishna Janmashtami",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Krishna Paksha Ashtami in Bhadrapada month.",
        "fixed_date": "2026-09-03",
        "end_date": "2026-09-04",
        "description": "Birth celebration of Krishna with fasting, midnight puja, and devotional singing.",
    },
    {
        "id": "asalha_puja",
        "name": "Asalha Puja",
        "type": "observance",
        "category": "other",
        "rule_hint": "Buddhist observance of the first teaching.",
        "fixed_date": "2026-09-08",
        "end_date": "2026-09-15",
        "description": "Buddhist observance marking the first discourse and the turning of the Dharma wheel.",
    },
    {
        "id": "paryushana",
        "name": "Paryushana",
        "type": "observance",
        "category": "other",
        "rule_hint": "Jain annual period of reflection, fasting, and forgiveness.",
        "fixed_date": "2026-09-08",
        "end_date": "2026-09-15",
        "description": "Jain observance centered on introspection, forgiveness, and spiritual discipline.",
    },
    {
        "id": "hanuman_jayanti",
        "name": "Hanuman Jayanti",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Regional observance; Europe-facing editorial date for MVP.",
        "fixed_date": "2026-09-03",
        "end_date": "2026-09-04",
        "description": "Devotional observance honoring Hanuman through prayer, chanting, and seva.",
    },
    {
        "id": "ganesh_chaturthi",
        "name": "Ganesh Chaturthi",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Shukla Paksha Chaturthi in Bhadrapada month.",
        "fixed_date": "2026-09-14",
        "description": "Festival welcoming Ganesha with home and community worship, music, and offerings.",
    },
    {
        "id": "pitru_paksha",
        "name": "Pitru Paksha",
        "type": "observance",
        "category": "observance",
        "rule_hint": "Fortnight for ancestral remembrance.",
        "fixed_date": "2026-09-26",
        "end_date": "2026-10-09",
        "description": "Period of remembrance, offerings, and gratitude for ancestors.",
    },
    {
        "id": "gandhi_jayanti",
        "name": "Gandhi Jayanti",
        "type": "observance",
        "category": "observance",
        "rule_hint": "Birth anniversary of Mahatma Gandhi.",
        "fixed_date": "2026-10-02",
        "description": "Day for reflection on ahimsa, civic responsibility, and service.",
    },
    {
        "id": "durga_puja",
        "name": "Durga Puja",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Autumnal worship of Durga over several days.",
        "fixed_date": "2026-10-11",
        "end_date": "2026-10-19",
        "description": "Multi-day autumn celebration of Durga through worship, artistry, and community gatherings.",
    },
    {
        "id": "navaratri",
        "name": "Navaratri",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Nine nights starting Shukla Paksha Pratipada in Ashwin month.",
        "fixed_date": "2026-10-11",
        "end_date": "2026-10-19",
        "description": "Nine nights of devotion, dance, fasting, and celebration of the divine feminine.",
    },
    {
        "id": "dussehra",
        "name": "Dussehra",
        "type": "main_festival",
        "category": "deity",
        "rule_hint": "Vijayadashami observance following Navaratri.",
        "fixed_date": "2026-10-20",
        "description": "Celebration of victory, dharma, and renewal at the close of Navaratri.",
    },
    {
        "id": "diwali",
        "name": "Diwali",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Amavasya in Kartik month; puja window in Pradosh Kaal after sunset.",
        "fixed_date": "2026-10-20",
        "description": "Festival of lights honoring renewal, prosperity, and the return of sacred light.",
    },
    {
        "id": "onam",
        "name": "Onam",
        "type": "main_festival",
        "category": "festival",
        "rule_hint": "Harvest festival celebrated with floral designs and feasts.",
        "fixed_date": "2026-10-28",
        "description": "Seasonal homecoming festival marked by feasts, floral art, and shared abundance.",
    },
    {
        "id": "mahavir_jayanti",
        "name": "Mahavir Jayanti",
        "type": "observance",
        "category": "other",
        "rule_hint": "Jain observance honoring Mahavira.",
        "fixed_date": "2026-11-24",
        "description": "Jain celebration honoring Mahavira through prayer, charity, and nonviolence.",
    },
    {
        "id": "nanak_jayanti",
        "name": "Nanak Jayanti",
        "type": "observance",
        "category": "other",
        "rule_hint": "Sikh observance of Guru Nanak's birth anniversary.",
        "fixed_date": "2026-11-25",
        "description": "Sikh observance honoring Guru Nanak through prayer, kirtan, and service.",
    },
    {
        "id": "karwa_chauth",
        "name": "Karwa Chauth",
        "type": "observance",
        "category": "festival",
        "rule_hint": "Married women's fast observed by moonrise.",
        "fixed_date": "2026-11-08",
        "description": "Fasting observance centered on prayer, family bonds, and evening moon sighting.",
    },
    {
        "id": "gita_jayanti",
        "name": "Gita Jayanti",
        "type": "observance",
        "category": "deity",
        "rule_hint": "Commemoration of the Bhagavad Gita's revelation.",
        "fixed_date": "2026-12-19",
        "description": "Day for scriptural study, contemplation, and recitation of the Bhagavad Gita.",
    },
]
